export const previewRoutes = [
  "/preview",
  "/preview/home/normal",
  "/preview/home/loading",
  "/preview/home/error",
  "/preview/home/no-daily",
  "/preview/home/daily-unplayable",
  "/preview/home/daily-closed",
  "/preview/home/daily-incomplete",
  "/preview/home/member-live",
  "/preview/daily/normal",
  "/preview/daily/loading",
  "/preview/daily/error",
  "/preview/daily/no-run",
  "/preview/daily/unplayable",
  "/preview/daily/unplayable-member",
  "/preview/daily/incomplete",
  "/preview/daily/closed",
  "/preview/lobby/landing",
  "/preview/lobby/loading",
  "/preview/lobby/creating",
  "/preview/lobby/joining-by-code",
  "/preview/lobby/joining-error",
  "/preview/lobby/waiting",
  "/preview/lobby/question",
  "/preview/lobby/reveal",
  "/preview/lobby/finished",
  "/preview/lobby/error",
  "/preview/profile/full",
  "/preview/profile/loading",
  "/preview/profile/error",
  "/preview/profile/not-found",
  "/preview/profile/empty",
  "/preview/profile/partial",
  "/preview/profile/other-member",
  "/preview/admin/normal",
  "/preview/admin/loading",
  "/preview/admin/forbidden",
  "/preview/admin/error",
  "/preview/admin/warnings",
  "/preview/admin/errors",
  "/preview/admin/no-runs",
  "/preview/onboarding/empty",
  "/preview/onboarding/filled",
];

export const previewShots = [
  { screen: "home", variant: "normal" },
  { screen: "home", variant: "loading" },
  { screen: "home", variant: "error" },
  { screen: "home", variant: "no-daily" },
  { screen: "home", variant: "daily-unplayable" },
  { screen: "home", variant: "daily-closed" },
  { screen: "home", variant: "daily-incomplete" },
  { screen: "home", variant: "member-live" },
  { screen: "daily", variant: "normal" },
  { screen: "daily", variant: "loading" },
  { screen: "daily", variant: "error" },
  { screen: "daily", variant: "no-run" },
  { screen: "daily", variant: "unplayable" },
  { screen: "daily", variant: "unplayable-member" },
  { screen: "daily", variant: "incomplete" },
  { screen: "daily", variant: "closed" },
  { screen: "lobby", variant: "landing" },
  { screen: "lobby", variant: "loading" },
  { screen: "lobby", variant: "creating" },
  { screen: "lobby", variant: "joining-by-code" },
  { screen: "lobby", variant: "joining-error" },
  { screen: "lobby", variant: "waiting" },
  { screen: "lobby", variant: "question" },
  { screen: "lobby", variant: "reveal" },
  { screen: "lobby", variant: "finished" },
  { screen: "lobby", variant: "error" },
  { screen: "profile", variant: "full" },
  { screen: "profile", variant: "loading" },
  { screen: "profile", variant: "error" },
  { screen: "profile", variant: "not-found" },
  { screen: "profile", variant: "empty" },
  { screen: "profile", variant: "partial" },
  { screen: "profile", variant: "other-member" },
  { screen: "admin", variant: "normal" },
  { screen: "admin", variant: "loading" },
  { screen: "admin", variant: "warnings" },
  { screen: "admin", variant: "errors" },
  { screen: "admin", variant: "no-runs" },
  { screen: "admin", variant: "forbidden" },
  { screen: "admin", variant: "error" },
  { screen: "onboarding", variant: "empty" },
  { screen: "onboarding", variant: "filled" },
];
